parent:
  image:
    registry: 929572853995.dkr.ecr.eu-west-1.amazonaws.com
    app: file-convert/app
    service: example-service
    tag: latest
    pullPolicy: Always
  service:
    port: 80
    type: ClusterIP
  deployment:
    replicas: 1
  container:
    port: 8080
    host: 127.0.0.1
  ingress:
    path: /api/example
    stripPrefix: true
  host: file-convert.online
  enableServiceLinks: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envVars:
    - name: ENV
      value: dev
    - name: HOST
      value: file-convert.online
    - name: APP_PORT
      value: 8080
    - name: EMAIL_SERVICE_URL
      value: http://email-service/send-email
  secretEnvVars:
    - name: DB_URI
      secretName: fc-example-dev-db-pguser-example-user
      secretKey: uri
    - name: JWT_SECRET
      secretName: fc-example-dev-jwt-secret
      secretKey: secret