apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    kubernetes.infra.app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: v1
    spec:
      enableServiceLinks: {{ default false .Values.enableServiceLinks }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- else if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.app }}/{{ .Values.image.service }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          {{- end }}
          {{- if .Values.ingress.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          env:
            - name: HOST
              value: {{ .Values.host | quote }}
            - name: ENV
              value: {{ default "" .Values.environment | quote }}
            {{- if .Values.ingress.enabled }}
            - name: SWAGGER_BASE_PATH
              value: {{ default "" .Values.ingress.path | quote }}
            - name: SWAGGER_SCHEMES
              value: {{ if or (eq .Values.environment "dev") (eq .Values.environment "staging") }}"https"{{ else }}"http"{{ end }}
            {{- end }}
            # Add environment variables if any
            {{- if .Values.envVars }}
            {{- range $env := .Values.envVars }}
            {{- if $env.valueFrom }}
            - name: {{ $env.name }}
              valueFrom:
                {{- toYaml $env.valueFrom | nindent 16 }}
            {{- else }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            # Add secret environment variables if any
            {{- if .Values.secretEnvVars }}
            {{- range $secret := .Values.secretEnvVars }}
            - name: {{ $secret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.secretName }}
                  key: {{ $secret.secretKey }}
            {{- end }}
            {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
