apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      middlewares:
      - name: {{ .Release.Name }}
      kind: Rule
      services:
        - kind: Service
          name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.path }}