{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service-deployment-helm-chart.fullname" . }}
  labels:
    {{- include "service-deployment-helm-chart.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "service-deployment-helm-chart.selectorLabels" . | nindent 6 }}
{{- end }} 