{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ default .Release.Namespace .Values.serviceAccount.namespace }}
  labels:
    app: {{ .Release.Name }}
    service: {{ .Release.Name }}
    environment: {{ .Values.environment | quote }}
{{- end }}