apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
    {{- include "service-deployment.selectorLabels" . | nindent 4 }}
    app_id: {{ include "service-deployment.appId" . }}
    {{- if .Values.serviceMonitor.enabled }}
    monitoring: "true"
    {{- end }}
spec:
  selector:
    {{- include "service-deployment.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.container.metricsPort }}
      targetPort: metrics
  type: {{ .Values.service.type }}
